### ISSUE TITLE
Bulk HDI filed out of order in WGBS version

### ISSUE THREAD

**Issue by Lesky47** [VanLoo-lab/CAMDAC#11]
https://github.com/VanLoo-lab/CAMDAC/blob/13113f8a473c0c9170922693d2f5c08510e238e4/R/asm_cmain.R#L397C15-L397C20
data.table::merge has sort=TRUE by default and the returned HDI object doesn't match the original methylation counts.

**Comment by NMNS93** [comment]
Fixed in #15
